// Date: 9/3/2019 6:53:44 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.favouritedragon.arcaneessentials.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelIceSpikeSlanted extends ModelBase
{
  //fields
    ModelRenderer iThornB1;
    ModelRenderer iThornB2;
    ModelRenderer iThornB3;
    ModelRenderer iThornB4;
  
  public ModelIceSpikeSlanted()
  {
    textureWidth = 100;
    textureHeight = 50;
    
      iThornB1 = new ModelRenderer(this, 0, 0);
      iThornB1.addBox(-5F, 0F, -5F, 10, 16, 10);
      iThornB1.setRotationPoint(3F, 10F, 0F);
      iThornB1.setTextureSize(64, 32);
      iThornB1.mirror = true;
      setRotation(iThornB1, 0F, 0F, 0.2617994F);
      iThornB2 = new ModelRenderer(this, 41, 0);
      iThornB2.addBox(-4F, 0F, -4F, 8, 11, 8);
      iThornB2.setRotationPoint(6.3F, -0.5F, 0F);
      iThornB2.setTextureSize(64, 32);
      iThornB2.mirror = true;
      setRotation(iThornB2, 0F, 0F, 0.2617994F);
      iThornB3 = new ModelRenderer(this, 0, 27);
      iThornB3.addBox(-3F, 0F, -3F, 6, 8, 6);
      iThornB3.setRotationPoint(8.7F, -8F, 0F);
      iThornB3.setTextureSize(64, 32);
      iThornB3.mirror = true;
      setRotation(iThornB3, 0F, 0F, 0.2617994F);
      iThornB4 = new ModelRenderer(this, 25, 27);
      iThornB4.addBox(-1.5F, 0F, -1.5F, 3, 5, 3);
      iThornB4.setRotationPoint(10.5F, -12.6F, 0F);
      iThornB4.setTextureSize(64, 32);
      iThornB4.mirror = true;
      setRotation(iThornB4, 0F, 0F, 0.2792527F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(entity, f, f1, f2, f3, f4, f5);
    iThornB1.render(f5);
    iThornB2.render(f5);
    iThornB3.render(f5);
    iThornB4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  private void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
