// Date: 9/3/2019 6:53:01 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package com.favouritedragon.arcaneessentials.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelIceSpikeVertical extends ModelBase {
	//fields
    private ModelRenderer iThornA1;
	private ModelRenderer iThornA2;
	private ModelRenderer iThornA3;
	private ModelRenderer iThornA4;

	public ModelIceSpikeVertical() {
		textureWidth = 100;
		textureHeight = 50;

		iThornA1 = new ModelRenderer(this, 0, 0);
		iThornA1.addBox(-5F, 0F, -5F, 10, 16, 10);
		iThornA1.setRotationPoint(0F, 8F, 0F);
		iThornA1.setTextureSize(64, 32);
		iThornA1.mirror = true;
		setRotation(iThornA1, 0F, 0F, 0F);
		iThornA2 = new ModelRenderer(this, 41, 0);
		iThornA2.addBox(-4F, 0F, -4F, 8, 11, 8);
		iThornA2.setRotationPoint(0F, -3F, 0F);
		iThornA2.setTextureSize(64, 32);
		iThornA2.mirror = true;
		setRotation(iThornA2, 0F, 0F, 0F);
		iThornA3 = new ModelRenderer(this, 0, 27);
		iThornA3.addBox(-3F, 0F, -3F, 6, 8, 6);
		iThornA3.setRotationPoint(0F, -11F, 0F);
		iThornA3.setTextureSize(64, 32);
		iThornA3.mirror = true;
		setRotation(iThornA3, 0F, 0F, 0F);
		iThornA4 = new ModelRenderer(this, 25, 27);
		iThornA4.addBox(-1.5F, 0F, -1.5F, 3, 5, 3);
		iThornA4.setRotationPoint(0F, -16F, 0F);
		iThornA4.setTextureSize(64, 32);
		iThornA4.mirror = true;
		setRotation(iThornA4, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(entity, f, f1, f2, f3, f4, f5);
		iThornA1.render(f5);
		iThornA2.render(f5);
		iThornA3.render(f5);
		iThornA4.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
